version: "3.9"

services:
  registration_service:
    container_name: register
    hostname: register
    build:
      context: ..
      dockerfile: ./Code/Docker/register_dockerfile
    network_mode: host
  peer_service:
    build:
      context: ..
      dockerfile: ./Code/Docker/peer_dockerfile
    depends_on:
      - registration_service
    deploy:
      mode: replicated
      replicas: ${PEERS}
    network_mode: host